baseURL = 'https://swe-agent.github.io/traj-viewer-mini'
languageCode = 'en-us'
title = 'Trajectory Viewer'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Mini Agent Trajectory Browser"
